apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: llm-serving
  region: us-east-1

managedNodeGroups:
  - name: gpu-od
    instanceTypes: ["g5.xlarge", "g5.2xlarge"]
    desiredCapacity: 0
    minSize: 0
    maxSize: 2
    volumeSize: 100
    volumeEncrypted: true
    tags:
      Project: llm-serving
      Owner: Joseph
      Environment: personal-lab
      TeardownPolicy: same-day
    labels:
      workload: gpu
    taints:
      - key: nvidia.com/gpu
        value: "true"
        effect: NoSchedule
